import { PageHeader } from '../components/layout/PageHeader.js';
import { Card } from '../components/ui/Card.js';
import { Badge } from '../components/ui/Badge.js';
import { ShieldCheck, Eye, WifiOff, FileText, Activity } from 'lucide-react';

export function LimitationsPage() {
  const limitations = [
    {
      title: 'AI Model Assessment vs Official Warning',
      icon: FileText,
      desc: 'All predictions and alerts generated by ERROR 404 represent automated AI/model-based evaluations. They do not constitute official statutory weather warnings or legal evacuation directives issued by national meteorological departments (e.g. IMD, NDMA).',
    },
    {
      title: 'Doppler Radar Line-of-Sight Coverage',
      icon: Eye,
      desc: 'Sub-kilometer quantitative precipitation estimation (QPE) relies on active Doppler Weather Radar (DWR) mosaic streams. In regions where radar beams are blocked by complex mountainous terrain or unconfigured, the system reports RADAR_UNAVAILABLE rather than hallucinating signals.',
    },
    {
      title: 'Data Quality Freshness Gate (>30 min)',
      icon: WifiOff,
      desc: 'If meteorological telemetry age exceeds 30 minutes (1800s) without real-time updates from sensor feeds, the Risk Intelligence Engine automatically halts evaluation and outputs RISK_UNAVAILABLE rather than computing fabricated risk indices.',
    },
    {
      title: 'Extreme Event Historical Scarcity',
      icon: Activity,
      desc: 'Severe cloudbursts (>100 mm/h) represent rare statistical outliers. While historical reanalysis provides robust training for convective cells up to 80 mm/h, unprecedented extreme meteorological anomalies carry higher predictive uncertainty scores.',
    },
  ];

  return (
    <div className="space-y-6 font-mono text-xs max-w-6xl mx-auto">
      <PageHeader
        title="TRANSPARENT SCIENTIFIC & OPERATIONAL LIMITATIONS"
        subtitle="Full disclosure of meteorological boundary conditions, sensor coverage dependencies, and operational safety guardrails."
        badge={
          <Badge variant="secondary" dot>
            HONEST SCIENTIFIC DISCLOSURE
          </Badge>
        }
      />

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {limitations.map((lim) => {
          const Icon = lim.icon;
          return (
            <Card key={lim.title} className="p-5 bg-card/60 backdrop-blur-sm border-amber-500/30 space-y-2.5">
              <div className="flex items-center gap-2 border-b border-border/40 pb-2">
                <div className="p-2 rounded bg-amber-950/40 border border-amber-500/30 text-amber-300">
                  <Icon className="w-4 h-4" />
                </div>
                <h3 className="font-bold text-foreground text-xs">{lim.title}</h3>
              </div>

              <p className="text-muted-foreground text-[11px] leading-relaxed pt-1">
                {lim.desc}
              </p>
            </Card>
          );
        })}
      </div>

      <Card className="p-5 bg-card/60 backdrop-blur-sm border-border/70 space-y-2">
        <div className="flex items-center gap-2">
          <ShieldCheck className="w-4 h-4 text-emerald-400" />
          <h4 className="font-bold text-foreground text-xs">Fail-Safe Design Principles</h4>
        </div>
        <p className="text-muted-foreground text-[11px] leading-relaxed">
          ERROR 404 adheres strictly to the <strong>No-Fabrication Policy</strong>. If a data source, radar feed, or model checkpoint is missing or degraded, the platform explicitly flags the affected subsystem as <code>DEGRADED</code>, <code>NOT CONFIGURED</code>, or <code>UNAVAILABLE</code> across all administrative, judge, and citizen interfaces.
        </p>
      </Card>
    </div>
  );
}
